"""Inspectra Full Stage 5 Schema

Revision ID: 5e050f9920a7
Revises: 
Create Date: 2026-09-03 23:29:15.105790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e050f9920a7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('csr_needs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('district', sa.String(), nullable=False),
    sa.Column('city_locality', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('beneficiary_type', sa.String(), nullable=False),
    sa.Column('beneficiary_count', sa.Integer(), nullable=False),
    sa.Column('urgency', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='urgencyenum'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='priorityenum'), nullable=True),
    sa.Column('priority_score', sa.Integer(), nullable=True),
    sa.Column('priority_reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('NEED_IDENTIFIED', 'AI_ASSESSMENT', 'NGO_MATCHING', 'NGO_SHORTLISTED', 'PARTNERSHIP_DISCUSSION', 'PROJECT_INITIATED', 'COMPLETED', name='statusenum'), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_identified_category', sa.String(), nullable=True),
    sa.Column('ai_beneficiary_group', sa.String(), nullable=True),
    sa.Column('ai_required_intervention', sa.String(), nullable=True),
    sa.Column('ai_key_need', sa.String(), nullable=True),
    sa.Column('ai_analysis', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('beneficiary_count >= 0', name='check_beneficiary_count_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_csr_needs_category'), 'csr_needs', ['category'], unique=False)
    op.create_index(op.f('ix_csr_needs_district'), 'csr_needs', ['district'], unique=False)
    op.create_index(op.f('ix_csr_needs_id'), 'csr_needs', ['id'], unique=False)
    op.create_index(op.f('ix_csr_needs_state'), 'csr_needs', ['state'], unique=False)
    op.create_index(op.f('ix_csr_needs_status'), 'csr_needs', ['status'], unique=False)
    op.create_table('csr_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('ngo', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_csr_projects_id'), 'csr_projects', ['id'], unique=False)
    op.create_table('ngos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('sectors', sa.String(), nullable=False),
    sa.Column('locations', sa.String(), nullable=False),
    sa.Column('beneficiary_types', sa.String(), nullable=False),
    sa.Column('experience', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ngos_id'), 'ngos', ['id'], unique=False)
    op.create_index(op.f('ix_ngos_locations'), 'ngos', ['locations'], unique=False)
    op.create_index(op.f('ix_ngos_name'), 'ngos', ['name'], unique=False)
    op.create_index(op.f('ix_ngos_sectors'), 'ngos', ['sectors'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('csr_need_id', sa.Integer(), nullable=False),
    sa.Column('ngo_id', sa.Integer(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('sector_match', sa.Float(), nullable=False),
    sa.Column('location_match', sa.Float(), nullable=False),
    sa.Column('beneficiary_match', sa.Float(), nullable=False),
    sa.Column('experience_match', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['csr_need_id'], ['csr_needs.id'], ),
    sa.ForeignKeyConstraint(['ngo_id'], ['ngos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_id'), 'matches', ['id'], unique=False)
    op.create_table('status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('csr_need_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('NEED_IDENTIFIED', 'AI_ASSESSMENT', 'NGO_MATCHING', 'NGO_SHORTLISTED', 'PARTNERSHIP_DISCUSSION', 'PROJECT_INITIATED', 'COMPLETED', name='statusenum'), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['csr_need_id'], ['csr_needs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_status_history_id'), 'status_history', ['id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('csr_need_id', sa.Integer(), nullable=False),
    sa.Column('ngo_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['csr_need_id'], ['csr_needs.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['ngo_id'], ['ngos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_id'), 'recommendations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendations_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_status_history_id'), table_name='status_history')
    op.drop_table('status_history')
    op.drop_index(op.f('ix_matches_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_ngos_sectors'), table_name='ngos')
    op.drop_index(op.f('ix_ngos_name'), table_name='ngos')
    op.drop_index(op.f('ix_ngos_locations'), table_name='ngos')
    op.drop_index(op.f('ix_ngos_id'), table_name='ngos')
    op.drop_table('ngos')
    op.drop_index(op.f('ix_csr_projects_id'), table_name='csr_projects')
    op.drop_table('csr_projects')
    op.drop_index(op.f('ix_csr_needs_status'), table_name='csr_needs')
    op.drop_index(op.f('ix_csr_needs_state'), table_name='csr_needs')
    op.drop_index(op.f('ix_csr_needs_id'), table_name='csr_needs')
    op.drop_index(op.f('ix_csr_needs_district'), table_name='csr_needs')
    op.drop_index(op.f('ix_csr_needs_category'), table_name='csr_needs')
    op.drop_table('csr_needs')
    # ### end Alembic commands ###
