"""Add NGO documents

Revision ID: a7d74d3df4e1
Revises: fb25dee38a9c
Create Date: 2026-09-04 06:34:08.825927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7d74d3df4e1'
down_revision: Union[str, Sequence[str], None] = 'fb25dee38a9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ngo_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ngo_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_reference', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('NOT_SUBMITTED', 'SUBMITTED', 'UNDER_REVIEW', 'VERIFIED', 'REQUIRES_ATTENTION', name='documentstatusenum', create_constraint=True), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ngo_id'], ['ngos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ngo_documents_id'), 'ngo_documents', ['id'], unique=False)
    op.create_index(op.f('ix_ngo_documents_ngo_id'), 'ngo_documents', ['ngo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ngo_documents_ngo_id'), table_name='ngo_documents')
    op.drop_index(op.f('ix_ngo_documents_id'), table_name='ngo_documents')
    op.drop_table('ngo_documents')
    # ### end Alembic commands ###
